import './AnswerPanel.css'
function HighlightedContext({ context, start, end }) { return <p className="context-text">{context.slice(0, start)}<mark className="context-highlight">{context.slice(start, end)}</mark>{context.slice(end)}</p> }
function ConfidenceMeter({ score }) { const pct = Math.round(score * 100); return <div className="confidence"><div className="confidence-track"><div className="confidence-fill" style={{ width: `${pct}%` }} /></div><span className="confidence-label">{pct}% confidence</span></div> }
export default function AnswerPanel({ result, error, asking, hasDocuments, history }) {
  if (asking) return <div className="answer-panel"><div className="loading-answer"><span className="loader"/><div><b>Searching your sources</b><p>Finding the most relevant passages...</p></div></div></div>
  if (error) return <div className="answer-panel"><div className="answer-error"><p className="answer-error-title">Couldn't find an answer</p><p className="answer-error-detail">{error}</p></div></div>
  if (!hasDocuments) return <div className="answer-panel"><div className="empty-state"><div className="empty-icon">↗</div><p>Your library is ready for its first source.</p><p className="empty-state-sub">Add a PDF, text file, or markdown document to begin asking questions.</p></div></div>
  if (!result) return <div className="answer-panel"><div className="empty-state"><div className="empty-icon">✦</div><p>Ready when you are.</p><p className="empty-state-sub">Ask a question and I’ll pull the answer straight from your documents.</p></div></div>
  return <div className="answer-panel"><div className="answer-block"><div className="answer-label"><span>✦</span> Answer from your library</div><p className="answer-text">{result.answer}</p><div className="answer-meta"><ConfidenceMeter score={result.score} /><div className="answer-actions"><button onClick={() => navigator.clipboard?.writeText(result.answer)}>Copy</button><button aria-label="Mark answer helpful">♡</button></div></div><div className="source-block"><p className="source-label"><span className="source-icon">▤</span> Found in <span className="source-doc-title">{result.doc_title}</span></p><HighlightedContext context={result.context} start={result.answer_start} end={result.answer_end} /></div></div>{history.length > 1 && <div className="history-block"><span className="rail-eyebrow">Earlier in this session</span><ul className="history-list">{history.slice(1).map((h, i) => <li key={i}><span className="history-q">{h.question}</span><span className="history-a">{h.answer}</span></li>)}</ul></div>}</div>
}
